// <auto-generated />
using System;
using AMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225140617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId")
                        .HasName("PK__Admins__719FE4882C0EACCB");

                    b.HasIndex(new[] { "UserId" }, "UQ__Admins__1788CC4D187583B8")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AMS.Models.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int?>("MarkedBy")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Absent");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69261C27B44320");

                    b.HasIndex("MarkedBy");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("AMS.Models.Entities.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("BatchId")
                        .HasName("PK__Batches__5D55CE580E6F1491");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("AMS.Models.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CourseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreditHours")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__C92D71A718B957C6");

                    b.HasIndex(new[] { "CourseCode" }, "UQ__Courses__FC00E0008DE7A2DC")
                        .IsUnique()
                        .HasFilter("[CourseCode] IS NOT NULL");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AMS.Models.Entities.CourseAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId")
                        .HasName("PK__CourseAs__32499E77E68389CE");

                    b.HasIndex("BatchId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseAssignments");
                });

            modelBuilder.Entity("AMS.Models.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__7F68771B48B20095");

                    b.HasIndex("BatchId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("AMS.Models.Entities.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__043301DDDBF242CD");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("AMS.Models.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("CourseAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SessionId")
                        .HasName("PK__Sessions__C9F492903CE85F74");

                    b.HasIndex("CourseAssignmentId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AMS.Models.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RollNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52B9990F352E7");

                    b.HasIndex("BatchId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Students__1788CC4D671FEA16")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.HasIndex(new[] { "RollNumber" }, "UQ__Students__E9F06F169BC6B808")
                        .IsUnique()
                        .HasFilter("[RollNumber] IS NOT NULL");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AMS.Models.Entities.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SettingId");

                    b.HasIndex(new[] { "SettingKey" }, "UQ_SystemSettings_SettingKey")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("AMS.Models.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId")
                        .HasName("PK__Teachers__EDF25964FB258040");

                    b.HasIndex(new[] { "UserId" }, "UQ__Teachers__1788CC4DAE73BFF3")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("AMS.Models.Entities.Timetable", b =>
                {
                    b.Property<int>("TimetableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimetableId"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("TimetableId")
                        .HasName("PK__Timetabl__68413F60DB556449");

                    b.HasIndex("BatchId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("AMS.Models.Entities.TimetableSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int?>("CourseAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TimetableId")
                        .HasColumnType("int");

                    b.HasKey("SlotId")
                        .HasName("PK__Timetabl__0A124AAF4B80EF0A");

                    b.HasIndex("CourseAssignmentId");

                    b.HasIndex("TimetableId");

                    b.ToTable("TimetableSlots");
                });

            modelBuilder.Entity("AMS.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C9469E077");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4B5590FF6")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534D58440E5")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AMS.Models.Entities.Admin", b =>
                {
                    b.HasOne("AMS.Models.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("AMS.Models.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Admins__UserId__412EB0B6");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AMS.Models.Entities.Attendance", b =>
                {
                    b.HasOne("AMS.Models.Entities.User", "MarkedByNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("MarkedBy")
                        .HasConstraintName("FK__Attendanc__Marke__6B24EA82");

                    b.HasOne("AMS.Models.Entities.Session", "Session")
                        .WithMany("Attendances")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK__Attendanc__Sessi__6754599E");

                    b.HasOne("AMS.Models.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Attendanc__Stude__68487DD7");

                    b.Navigation("MarkedByNavigation");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AMS.Models.Entities.CourseAssignment", b =>
                {
                    b.HasOne("AMS.Models.Entities.Batch", "Batch")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK__CourseAss__Batch__5812160E");

                    b.HasOne("AMS.Models.Entities.Course", "Course")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__CourseAss__Cours__571DF1D5");

                    b.HasOne("AMS.Models.Entities.Semester", "Semester")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK__CourseAss__Semes__59063A47");

                    b.HasOne("AMS.Models.Entities.Teacher", "Teacher")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__CourseAss__Teach__5629CD9C");

                    b.Navigation("Batch");

                    b.Navigation("Course");

                    b.Navigation("Semester");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AMS.Models.Entities.Enrollment", b =>
                {
                    b.HasOne("AMS.Models.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId");

                    b.HasOne("AMS.Models.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Enrollmen__Cours__5DCAEF64");

                    b.HasOne("AMS.Models.Entities.Semester", "Semester")
                        .WithMany("Enrollments")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK__Enrollmen__Semes__5EBF139D");

                    b.HasOne("AMS.Models.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Enrollmen__Stude__5CD6CB2B");

                    b.Navigation("Batch");

                    b.Navigation("Course");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AMS.Models.Entities.Session", b =>
                {
                    b.HasOne("AMS.Models.Entities.CourseAssignment", "CourseAssignment")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseAssignmentId")
                        .HasConstraintName("FK__Sessions__Course__6383C8BA");

                    b.HasOne("AMS.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("Sessions")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Sessions__Create__6477ECF3");

                    b.Navigation("CourseAssignment");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("AMS.Models.Entities.Student", b =>
                {
                    b.HasOne("AMS.Models.Entities.Batch", "Batch")
                        .WithMany("Students")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK__Students__BatchI__4BAC3F29");

                    b.HasOne("AMS.Models.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("AMS.Models.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Students__UserId__4AB81AF0");

                    b.Navigation("Batch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AMS.Models.Entities.Teacher", b =>
                {
                    b.HasOne("AMS.Models.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("AMS.Models.Entities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Teachers__UserId__44FF419A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AMS.Models.Entities.Timetable", b =>
                {
                    b.HasOne("AMS.Models.Entities.Batch", "Batch")
                        .WithMany("Timetables")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK__Timetable__Batch__6E01572D");

                    b.HasOne("AMS.Models.Entities.Semester", "Semester")
                        .WithMany("Timetables")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK__Timetable__Semes__6EF57B66");

                    b.Navigation("Batch");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("AMS.Models.Entities.TimetableSlot", b =>
                {
                    b.HasOne("AMS.Models.Entities.CourseAssignment", "CourseAssignment")
                        .WithMany("TimetableSlots")
                        .HasForeignKey("CourseAssignmentId")
                        .HasConstraintName("FK__Timetable__Cours__73BA3083");

                    b.HasOne("AMS.Models.Entities.Timetable", "Timetable")
                        .WithMany("TimetableSlots")
                        .HasForeignKey("TimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Timetable__Timet__72C60C4A");

                    b.Navigation("CourseAssignment");

                    b.Navigation("Timetable");
                });

            modelBuilder.Entity("AMS.Models.Entities.Batch", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("Students");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("AMS.Models.Entities.Course", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("AMS.Models.Entities.CourseAssignment", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("TimetableSlots");
                });

            modelBuilder.Entity("AMS.Models.Entities.Semester", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("Enrollments");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("AMS.Models.Entities.Session", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("AMS.Models.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("AMS.Models.Entities.Teacher", b =>
                {
                    b.Navigation("CourseAssignments");
                });

            modelBuilder.Entity("AMS.Models.Entities.Timetable", b =>
                {
                    b.Navigation("TimetableSlots");
                });

            modelBuilder.Entity("AMS.Models.Entities.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Attendances");

                    b.Navigation("Sessions");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
